services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app/app
      - ./logs/api:/logs/api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      default: null
    ports:
      - "5050:80"
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin

  logs:
    image: alpine
    command: ["sh", "-c", "mkdir -p /logs/api /logs/postgres /logs/pgadmin && tail -f /dev/null"]
    volumes:
      - ./logs/api:/logs/api

volumes:
  postgres_data:
  pgadmin_data: